#cloud-config
# You will need to edit this file before creating your new servers
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBm/2zfjjNbabhVRzXEK4pOlCoW2l0/ov29UtZmmxKZn peterchenna@yahoo.com

packages:
  - ripgrep
  - rsync
  - ufw
  - nginx

runcmd:
  - sed -i 's/^#\(Storage=auto\)/\1/' /etc/systemd/journald.conf
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - systemctl restart systemd-journald
